name: Update Gist
on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Gist
        uses: bokub/github-stats-box@94129525049c55b512c1b827732298c9f80a4023
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
